---
# Either provide an appId and appSecret or a valid userToken
facebook:
  userToken: ''
  # appId: ''
  # appSecret: ''
database:
  host: 127.0.0.1
  user: root
  password: ''
  db: facebook
pages:
  # NPD
  - npd.de
  - junge.nationalisten
  - npdbw  # Baden-Württemberg
  - npdbayern  # Bayern
  - npd.berlin  # Berlin
  - npd.brandenburg  # Brandenburg
  - NpdBremen  # Bremen
  - npdhamburg  # Hamburg
  - npd.hessen  # Hessen
  - npdmup  # Mecklenburg-Vorpommern
  - npd.niedersachsen  # Niedersachsen
  - npdnrw  # Nordrhein-Westfalen
  - National.rlp  # Rheinland-Pfalz
  - npdsaar  # Saarland
  - npd.sachsen  # Sachsen
  # - NPD-Sachsen-Anhalt-627792194016177  # Sachsen-Anhalt
  - NPDSchleswigHolstein  # Schleswig-Holstein
  - npdthueringen  # Thüringen

  # AfD
  - alternativefuerde
  - jafuer.de  # Junge Alternative
  - AfD.BW  # Baden-Württemberg
  - afd.bayern  # Bayern
  - afdberlin  # Berlin
  - afd.brandenburg  # Brandenburg
  - afd.hb  # Bremen
  - afd.hamburg  # Hamburg
  # - Alternative-für-Deutschland-Hessen-AfD-222005461272345  # Hessen
  - AfD.MV  # Mecklenburg-Vorpommern
  - AfDNDS  # Niedersachsen
  - AfDfuerNRW  # Nordrhein-Westfalen
  - afdrheinlandpfalz  # Rheinland-Pfalz
  - AfDSaar  # Saarland
  - AfD.Fraktion.Sachsen  # Sachsen
  - SachsenAnhalt.AfD  # Sachsen-Anhalt
  - AfD.Schleswig.Holstein.de  # Schleswig-Holstein
  - AfD.Thueringen  # Thüringen

  # Other
  - pegidaevofficial # PEGIDA
  - merkelmusswegmittwoch

  # News
  - jungefreiheit
  - Compact.Magazin
  - PINEWSNET

  # People
  - ff.frankfranz  # NPD Parteivorsitzender Frank Franz
  - pegidalutz  # Lutz Bachmann, PEGIDA Initiator
  - MichaelSturzenberger  # Ehem. Bundesvorsitzender "Die Freiheit“

  # Patriot pages
  - patriotAUF
  - Deutsche.Patrioten.eK
  - FamilieVolkundHeimat

  # Other
  - ring.nationaler.frauen
  - Republikaner
startDate: 2008-01-01
