---
facebook:
  appId: '1861056970806187'
  appSecret: '4fcfb62b1e78d7b81a7b52298b0ec27a'
database:
  host: 127.0.0.1
  user: root
  password: ''
  db: facebook
pages:
  - npd.de
  - npdsaar
  - npdhamburg
  - npdthueringen
  - npd.niedersachsen
  - NPDSchleswigHolstein
  - npdmup
  - npd.sachsen
  - npdbayern
  - npd.brandenburg
  - ring.nationaler.frauen
  - FamilieVolkundHeimat
  - junge.nationalisten
startDate: 2017-01-01