name: racist
dependencies:
  - python=3.5
  - numpy
  - pip
  - pip:
    - mysql-connector==2.1.6
    - progressbar2
    - pyyaml
    - argparse
    - git+https://github.com/mobolic/facebook-sdk.git#egg=facebook-sdk
    - tensorflow